Repository microsoft/vscode-autopep8, pull requests merged in 2023-10, with the labels that each got.

#156 Fix config file setting in readme
  README.md
Labels: bug, documentation

#173 Python min/max version updates
  .github/actions/build-vsix/action.yml
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  noxfile.py
  package-lock.json
  package.json
  requirements.in
  requirements.txt
  runtime.txt
  src/common/python.ts
  src/extension.ts
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
Labels: debt

#174 Remove legacy settings support
  src/common/constants.ts
  src/common/settings.ts
  src/extension.ts
Labels: debt

#167 Capitalize python in readme and settings description
  README.md
  package.nls.json
Labels: debt

#175 Use narrow text edits and add range-formatting
  bundled/tool/lsp_edit_utils.py
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/lsp_test_client/utils.py
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_data/sample6/sample.py
  src/test/python_tests/test_data/sample6/sample.unformatted
  src/test/python_tests/test_edit_utils.py
  src/test/python_tests/test_formatting.py
Labels: bug
