Repository microsoft/vscode-autopep8, pull requests merged in 2023-06, with the labels that each got.

#103 Fixes from other extensions
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  noxfile.py
  package-lock.json
  package.json
  requirements.txt
  src/common/server.ts
  src/common/settings.ts
  src/extension.ts
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_formatting.py
Labels: debt

#106 Update logging and logging instructions
  README.md
  src/common/settings.ts
Labels: debt

#108 Set PYTHONUTF8 when running server
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  src/common/server.ts
  src/extension.ts
Labels: bug

#111 Engineering - add TSAOptions
  build/azure-pipeline.stable.yml
Labels: no-changelog

#115 Mark virtual workspaces as unsupported in package.json
  package.json
Labels: bug
