Repository microsoft/vscode-autopep8, pull requests merged in 2025-02, with the labels that each got.

#300 Update last compatible version with python 3.8
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
Labels: debt

#301 update to 2025.1.0
  package-lock.json
  package.json
Labels: no-changelog

#303 fix: bug where successive python changed events trigger creating multiple servers
  src/common/constants.ts
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/utilities.ts
  src/extension.ts
Labels: bug
